(* Generated by ocaml-tree-sitter. *)
(*
   haskell grammar

   entrypoint: haskell
*)

open! Sexplib.Conv
open Tree_sitter_run

type octal_literal = Token.t

type cond_minus = Token.t

type implicit_variable = Token.t

type hex_literal = Token.t

type cond_left_section_op = Token.t

type cond_prefix_at = Token.t

type string_ = Token.t

type cmd_layout_start_do = Token.t

type cond_tight_bang = Token.t

type imm_tok_bar = Token.t (* "|" *)

type arrow = [
    `DASHGT of Token.t (* "->" *)
  | `UNKUNKUNK of Token.t (* "\226\134\146" *)
]

type phantom_arrow = Token.t

type cond_prefix_tilde = Token.t

type do_keyword = [ `Mdo of Token.t (* "mdo" *) | `Do of Token.t (* "do" *) ]

type cmd_layout_start_explicit = Token.t

type tok_barrbrack = Token.t

type variable = Token.t

type cond_infix = Token.t

type cond_prefix_dot = Token.t

type pat_8b3e25a = Token.t (* pattern \) *)

type deriving_strategy = [
    `Stock of Token.t (* "stock" *)
  | `Newt of Token.t (* "newtype" *)
  | `Anyc of Token.t (* "anyclass" *)
]

type binary_literal = Token.t

type carrow = [
    `EQGT of Token.t (* "=>" *)
  | `UNKUNKUNK of Token.t (* "\226\135\146" *)
]

type forall_keyword = [
    `Forall of Token.t (* "forall" *)
  | `UNKUNKUNK of Token.t (* "\226\136\128" *)
]

type quasiquote_body = Token.t

type cmd_texp_start = Token.t

type cond_qual_dot = Token.t

type cmd_brace_close = Token.t

type type_star = [
    `STAR of Token.t (* "*" *)
  | `UNKUNKUNK of Token.t (* "\226\152\133" *)
]

type cond_tight_dot = Token.t

type cond_no_section_op = Token.t

type imm_tok_hash = Token.t (* "#" *)

type phantom_bar = Token.t

type name = Token.t

type cmd_layout_start_if = Token.t

type cond_prefix_percent = Token.t

type tok_barbarrbrack = Token.t

type cond_splice = Token.t

type cond_quote_start = Token.t

type larrow = [
    `LTDASH of Token.t (* "<-" *)
  | `UNKUNKUNK of Token.t (* "\226\134\144" *)
]

type cmd_brace_open = Token.t

type cond_tight_at = Token.t

type integer_literal = Token.t

type cond_qualified_op = Token.t

type cmd_layout_start_quote = Token.t

type cond_layout_semicolon = Token.t

type varsym = Token.t

type namespace = [
    `Pat of Token.t (* "pattern" *)
  | `Type of Token.t (* "type" *)
]

type pat_20dc0f2 = Token.t (* pattern \( *)

type phantom_deriving = Token.t

type char = Token.t

type cmd_layout_start = Token.t

type cond_prefix_bang = Token.t

type phantom_in = Token.t

type cond_layout_end_explicit = Token.t

type consym = Token.t

type cond_dotdot = Token.t

type fun_arrow_prec = (Token.t (* "-" *) * Token.t (* "1" *))

type cmd_layout_start_let = Token.t

type colon2 = [
    `COLONCOLON of Token.t (* "::" *)
  | `UNKUNKUNK of Token.t (* "\226\136\183" *)
]

type cond_tight_tilde = Token.t

type float_ = Token.t

type linear_arrow = [
    `DASHGTDOT of Token.t (* "->." *)
  | `UNKUNKUNK of Token.t (* "\226\138\184" *)
]

type cond_assoc_tyinst = Token.t

type phantom_where = Token.t

type safety = Token.t

type label = Token.t

type cond_context = Token.t

type type_role = [
    `Repr of Token.t (* "representational" *)
  | `Nomi of Token.t (* "nominal" *)
  | `Phan of Token.t (* "phantom" *)
  | `X__ of Token.t (* "_" *)
]

type cond_layout_end = Token.t

type cmd_texp_end = Token.t

type cmd_layout_start_case = Token.t

type cond_data_infix = Token.t

type calling_convention = Token.t

type prefix_at = (cond_prefix_at (*tok*) * Token.t (* "@" *))

type unboxed_bar = [
    `BAR of Token.t (* "|" *)
  | `Imm_tok_bar of imm_tok_bar (*tok*)
]

type fun_arrow = (phantom_arrow (*tok*) option * arrow)

type anon_choice_tok_barr_720cf3d = [
    `Tok_barr of tok_barrbrack (*tok*)
  | `UNKUNKUNK of Token.t (* "\226\159\167" *)
]

type prefix_dot = (cond_prefix_dot (*tok*) * Token.t (* "." *))

type bracket_open = (Token.t (* "[" *) * cmd_texp_start (*tok*))

type qual_dot = (cond_qual_dot (*tok*) * Token.t (* "." *))

type tight_dot = (cond_tight_dot (*tok*) * Token.t (* "." *))

type bar = (phantom_bar (*tok*) option * Token.t (* "|" *))

type prefix_percent = (cond_prefix_percent (*tok*) * Token.t (* "%" *))

type splice_dollars = (
    cond_splice (*tok*)
  * [ `DOLLAR of Token.t (* "$" *) | `DOLLARDOLLAR of Token.t (* "$$" *) ]
)

type tight_at = (cond_tight_at (*tok*) * Token.t (* "@" *))

type integer = [
    `Bin_lit of binary_literal (*tok*)
  | `Int_lit of integer_literal (*tok*)
  | `Octal_lit of octal_literal (*tok*)
  | `Hex_lit of hex_literal (*tok*)
]

type anon_choice_rep1_SEMI_eece391 = [
    `Rep1_SEMI of Token.t (* ";" *) list (* one or more *)
  | `Cond_layout_semi of cond_layout_semicolon (*tok*)
]

type operator_qual_dot_head = (cond_qual_dot (*tok*) * varsym (*tok*))

type paren_open = (pat_20dc0f2 * cmd_texp_start (*tok*))

type anon_choice_cmd_layout_start_adad0e7 = [
    `Cmd_layout_start of cmd_layout_start (*tok*)
  | `Cmd_layout_start_expl of cmd_layout_start_explicit (*tok*)
]

type dotdot = (cond_dotdot (*tok*) * Token.t (* ".." *))

type where = (phantom_where (*tok*) option * Token.t (* "where" *))

type layout_end = [
    `Cond_layout_end of cond_layout_end (*tok*)
  | `Cond_layout_end_expl of cond_layout_end_explicit (*tok*)
]

type bracket_close = (Token.t (* "]" *) * cmd_texp_end (*tok*))

type unboxed_close = (Token.t (* "#)" *) * cmd_texp_end (*tok*))

type paren_close = (pat_8b3e25a * cmd_texp_end (*tok*))

type anon_choice_cmd_layout_start_case_8ec747f = [
    `Cmd_layout_start_case of cmd_layout_start_case (*tok*)
  | `Cmd_layout_start_expl of cmd_layout_start_explicit (*tok*)
]

type stringly = [ `Str of string_ (*tok*) | `Char of char (*tok*) ]

type variable_ticked = (
    Token.t (* "`" *) * variable (*tok*) * Token.t (* "`" *)
)

type fundep = (
    variable (*tok*) list (* one or more *)
  * arrow
  * variable (*tok*) list (* one or more *)
)

type any_prefix_dot = [ `Qual_dot of qual_dot | `Prefix_dot of prefix_dot ]

type any_tight_dot = [ `Qual_dot of qual_dot | `Tight_dot of tight_dot ]

type operator = [
    `Opt_cond_prefix_dot_varsym of (
        cond_prefix_dot (*tok*) option
      * varsym (*tok*)
    )
  | `Op_hash_head of (
        [
            `HASH of Token.t (* "#" *)
          | `Imm_tok_hash of imm_tok_hash (*tok*)
        ]
      * [
            `Imm_tok_hash of imm_tok_hash (*tok*)
          | `Imm_tok_bar of imm_tok_bar (*tok*)
        ]
          option
    )
  | `STAR of Token.t (* "*" *)
]

type type_family_injectivity = (
    bar
  * variable (*tok*)
  * arrow
  * variable (*tok*) list (* one or more *)
)

type constructor_ticked = (
    Token.t (* "`" *) * name (*tok*) * Token.t (* "`" *)
)

type number = [ `Int of integer | `Float of float_ (*tok*) ]

type unboxed_open = (paren_open * imm_tok_hash (*tok*))

type any_prefix_bang = [
    `Prefix_bang of (cond_prefix_bang (*tok*) * Token.t (* "!" *))
  | `Tight_bang of (cond_tight_bang (*tok*) * Token.t (* "!" *))
]

type any_prefix_tilde = [
    `Prefix_tilde of (cond_prefix_tilde (*tok*) * Token.t (* "~" *))
  | `Tight_tilde of (cond_tight_tilde (*tok*) * Token.t (* "~" *))
]

type abstract_family = (
    anon_choice_cmd_layout_start_adad0e7 * Token.t (* ".." *) * layout_end
)

type plist = (bracket_open * bracket_close)

type prefix_tuple = (
    paren_open
  * Token.t (* "," *) list (* one or more *)
  * paren_close
)

type unit_ = (paren_open * paren_close)

type fundeps = (
    bar
  * fundep
  * (Token.t (* "," *) * fundep) list (* zero or more *)
)

type modid_prefix = (name (*tok*) * any_tight_dot)

type operator_alias = operator

type literal = [ `Choice_str of stringly | `Choice_int of number ]

type unboxed_unit = (unboxed_open * unboxed_close)

type conop = [
    `Cons_op_alias of consym (*tok*)
  | `Cons_ticked of constructor_ticked
]

type consym_prefix = (paren_open * consym (*tok*) * paren_close)

type qualifying_module = modid_prefix list (* one or more *)

type module_ = (modid_prefix list (* zero or more *) * name (*tok*))

type varop = [ `Op of operator_alias | `Var_ticked of variable_ticked ]

type varsym_prefix = (
    paren_open
  * [
        `Op of operator_alias
      | `Op_minus of Token.t (* "-" *)
      | `Op_qual_dot_head of operator_qual_dot_head
    ]
  * paren_close
)

type sym = [ `Op_alias of operator_alias | `Cons_op_alias of consym (*tok*) ]

type tuple_cons = [
    `Prefix_tuple of prefix_tuple
  | `Prefix_unbo_tuple of (
        unboxed_open
      * Token.t (* "," *) list (* one or more *)
      * unboxed_close
    )
  | `Prefix_unbo_sum of (
        unboxed_open
      * unboxed_bar list (* one or more *)
      * unboxed_close
    )
]

type unit_cons = [ `Unit of unit_ | `Unbo_unit of unboxed_unit ]

type pconsym = consym_prefix

type qualified_arrow = (qualifying_module * arrow)

type qualified_type = (qualifying_module * name (*tok*))

type qualified_variable = (qualifying_module * variable (*tok*))

type qualified_varsym = (
    qualifying_module
  * [ `Op of operator_alias | `Op_minus of Token.t (* "-" *) ]
)

type qualified_constructor = (qualifying_module * name (*tok*))

type qualified_consym = (qualifying_module * consym (*tok*))

type anon_choice_op_minus_21bd6a6 = [
    `Op_minus of Token.t (* "-" *)
  | `Choice_op of varop
  | `Choice_cons_op_alias of conop
]

type pvarsym = varsym_prefix

type con = [ `Name of name (*tok*) | `Pcon of pconsym ]

type do_ = [
    `Do_module of (qualifying_module * do_keyword)
  | `Do_kw of do_keyword
]

type qtyconid = qualified_type

type qvarid = qualified_variable

type qvarsym = qualified_varsym

type qconid = qualified_constructor

type qconsym = qualified_consym

type field_names = [
    `Field_name of variable (*tok*)
  | `Qfield_name of (qualifying_module * variable (*tok*))
]

type fixity = [
    `Fun_arrow_fixity of (
        Token.t (* "infixr" *) * fun_arrow_prec * Token.t (* "->" *)
    )
  | `Choice_infixl_opt_int_choice_op_minus_rep_COMMA_choice_op_minus of (
        [
            `Infixl of Token.t (* "infixl" *)
          | `Infixr of Token.t (* "infixr" *)
          | `Infix of Token.t (* "infix" *)
        ]
      * integer option
      * anon_choice_op_minus_21bd6a6
      * (Token.t (* "," *) * anon_choice_op_minus_21bd6a6)
          list (* zero or more *)
    )
]

type sym_prefix = [ `Pvar of pvarsym | `Pcon of pconsym ]

type function_name = [ `Var of variable (*tok*) | `Pvar of pvarsym ]

type tycon = [
    `Name of name (*tok*)
  | `Pvar of pvarsym
  | `Tycon_arrow of (paren_open * arrow * paren_close)
  | `Pcon of pconsym
]

type var = [ `Var of variable (*tok*) | `Pvar of pvarsym ]

type tyconids = [ `Qtyc of qtyconid | `Name of name (*tok*) ]

type quoter = [ `Qvarid of qvarid | `Var of variable (*tok*) ]

type qvarsym_prefix = (paren_open * qvarsym * paren_close)

type qsym = [ `Qual_varsym of qvarsym | `Qual_consym of qconsym ]

type qconsym_prefix = (paren_open * qconsym * paren_close)

type type_head_name = [
    `Choice_name of tycon
  | `Unit of unit_
  | `Plist of plist
]

type var_binding_list = (
    var
  * (Token.t (* "," *) * var) list (* one or more *)
)

type anon_choice_con_8c8f04c = [
    `Choice_name of con
  | `Con_bind_list of (
        con
      * (Token.t (* "," *) * con) list (* one or more *)
    )
]

type tyconids_ticked = [
    `Tycon_ticked of (Token.t (* "`" *) * name (*tok*) * Token.t (* "`" *))
  | `Qtycon_ticked of (Token.t (* "`" *) * qtyconid * Token.t (* "`" *))
]

type varids_ticked = [
    `Var_ticked of variable_ticked
  | `Qvar_ticked of (Token.t (* "`" *) * qvarid * Token.t (* "`" *))
]

type pqvarsym = qvarsym_prefix

type conids_ticked = [
    `Cons_ticked of constructor_ticked
  | `Qcon_ticked of (Token.t (* "`" *) * qconid * Token.t (* "`" *))
]

type pqconsym = qconsym_prefix

type field_spec = [
    `Field_names of field_names
  | `Field_path of (
        field_names
      * (tight_dot * variable (*tok*)) list (* one or more *)
    )
]

type tyconops = [
    `Choice_op_alias of sym
  | `Choice_qual_varsym of qsym
  | `Op_minus of Token.t (* "-" *)
  | `Tycons_ticked of tyconids_ticked
]

type qvar = [ `Qvarid of qvarid | `Pqva of pqvarsym ]

type op_ticked = [
    `Choice_var_ticked of varids_ticked
  | `Choice_cons_ticked of conids_ticked
]

type pqsym = [ `Pqva of pqvarsym | `Pqco of pqconsym ]

type qcon = [ `Qconid of qconid | `Pqco of pqconsym ]

type promoted_tyconops_alias = (Token.t (* "'" *) * tyconops)

type vars = [ `Choice_var of var | `Qvar of qvar ]

type exp_op = [
    `Choice_op_alias of sym
  | `Choice_choice_var_ticked of op_ticked
  | `Prefix_dot of prefix_dot
]

type ops = [
    `Op of operator_alias
  | `Qual_varsym of qvarsym
  | `Cons_op of consym (*tok*)
  | `Qual_consym of qconsym
  | `Choice_choice_var_ticked of op_ticked
]

type qtycon = [
    `Qtyc of qtyconid
  | `Qtycon_arrow of (paren_open * qualified_arrow * paren_close)
  | `Choice_pqva of pqsym
]

type cons = [ `Choice_name of con | `Choice_qconid of qcon ]

type tycons = [ `Choice_name of tycon | `Choice_qtyc of qtycon ]

type pat_name = [ `Choice_var of var | `Choice_choice_name of cons ]

type promoted_tycons_alias = (Token.t (* "'" *) * cons)

type exp_name = [
    `Choice_choice_name of cons
  | `Choice_choice_var of vars
  | `Var of variable (*tok*)
  | `Impl_var of implicit_variable (*tok*)
  | `Label of label (*tok*)
]

type qname = [ `Choice_choice_var of vars | `Choice_choice_name of cons ]

type tyops = [
    `Choice_choice_op_alias of tyconops
  | `Prom_tycons of (Token.t (* "'" *) * tyconops)
]

type child = [
    `Child_type of (Token.t (* "type" *) * tyconids)
  | `Qname of qname
]

type type_name = [
    `Var of variable (*tok*)
  | `Prom_tycons of (Token.t (* "'" *) * cons)
  | `Choice_choice_name of tycons
]

type anon_choice_DOTDOT_249879e = [
    `DOTDOT of Token.t (* ".." *)
  | `Child of child
]

type alternative = (pat * matches * where_binds option)

and alternatives = (
    anon_choice_cmd_layout_start_case_8ec747f
  * (
        anon_choice_rep1_SEMI_eece391 option
      * alternative
      * (anon_choice_rep1_SEMI_eece391 * alternative) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and anon_rep_COMMA_opt_exp_stmt_38c9686 =
  (Token.t (* "," *) * exp_statement option) list (* zero or more *)

and assoc_datainst = [
    `Assoc_data_adt of (
        Token.t (* "data" *)
      * Token.t (* "instance" *) option
      * inst_adt
    )
  | `Assoc_data_newt of (
        Token.t (* "newtype" *)
      * Token.t (* "instance" *) option
      * inst_newtype
    )
]

and assoc_tyinst = (
    Token.t (* "type" *)
  * Token.t (* "instance" *) option
  * forall_ option
  * cond_assoc_tyinst (*tok*)
  * type_instance_common
)

and at_type = (prefix_at * newtype_con_field)

and bind = (
    [
        `Pat of pat
      | `Choice_var of var
      | `Impl_var of implicit_variable (*tok*)
    ]
  * bind_matches
)

and bind_match = (
    guards_ * Token.t (* "=" *) * cmd_texp_end (*tok*) * exp_statement
)

and bind_matches = (
    [
        `Simple_bind_match of simple_bind_match
      | `Rep1_bind_match of bind_match list (* one or more *)
    ]
  * where_binds option
)

and class_decl = [
    `Local_decl of local_decl
  | `Defa_sign of (Token.t (* "default" *) * signature)
  | `Assoc_tyfam of (
        Token.t (* "type" *)
      * Token.t (* "family" *) option
      * type_head
      * [
            `Colon2_quan_type of type_annotation
          | `Type_family_result_type_family_inje of (
                type_family_result * type_family_injectivity
            )
        ]
          option
    )
  | `Assoc_tyinst of assoc_tyinst
  | `Assoc_data of (
        Token.t (* "data" *)
      * Token.t (* "family" *) option
      * datafam
    )
]

and class_declarations = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * class_decl
      * (anon_choice_rep1_SEMI_eece391 * class_decl) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and constraint_ = [
    `Choice_var of type_name
  | `Class_infix of (
        cond_infix (*tok*) * newtype_con_field * tyops * newtype_con_field
    )
  | `Class_apply of (constraint_ * type_apply_arg)
  | `Ctr_parens of (paren_open * constraints * paren_close)
  | `Ctr_tuple of (
        paren_open
      * constraints
      * (Token.t (* "," *) * constraints) list (* one or more *)
      * paren_close
    )
  | `Type_wild of Token.t (* "_" *)
  | `Choice_splice of universal
]

and constraints = [
    `Cons of constraint_
  | `Ctr_cont of (context * constraints)
  | `Ctr_forall of (forall_body * Token.t (* "." *) * constraints)
  | `Impl_param of implicit_parameter
  | `Ctr_sign of (constraints * colon2 * gadt_con_prefix)
]

and context = context_inline

and context_inline = (cond_context (*tok*) * constraint_ * carrow)

and data = (
    context option
  * type_head
  * data_rhs option
  * deriving list (* zero or more *)
)

and data_constructor = (
    forall_ option
  * context option
  * [
        `Data_prefix of datacon_prefix
      | `Data_infix of datacon_infix
      | `Data_record of datacon_record
      | `Data_spec of datacon_special
    ]
)

and data_constructors = (
    data_constructor
  * (bar * data_constructor) list (* zero or more *)
)

and data_instance = [
    `Decl_inst_adt of (
        Token.t (* "data" *) * Token.t (* "instance" *) * inst_adt
    )
  | `Decl_inst_newt of (
        Token.t (* "newtype" *) * Token.t (* "instance" *) * inst_newtype
    )
]

and data_rhs = [
    `Colon2_quan_type of type_annotation
  | `EQ_data_consts of (Token.t (* "=" *) * data_constructors)
  | `Gadt of gadt
]

and datacon_infix = (
    cond_data_infix (*tok*) * field_type * conop * field_type
)

and datacon_prefix = (con * field_type list (* zero or more *))

and datacon_record = (name (*tok*) * record_fields)

and datacon_special = [
    `Unit of unit_
  | `Unbo_unit of unboxed_unit
  | `Plist of plist
  | `Type_tuple of type_tuple
  | `Type_unbo_tuple of type_unboxed_tuple
  | `Data_unbo_sum of (
        unboxed_open
      * [
            `Rep1_choice_BAR_quan_type of (
                unboxed_bar list (* one or more *)
              * gadt_con_prefix
            )
          | `Quan_type_choice_BAR of (gadt_con_prefix * unboxed_bar)
        ]
      * unboxed_bar list (* zero or more *)
      * unboxed_close
    )
]

and datafam = (type_head * type_annotation option)

and decl = [
    `Sign of signature
  | `Func of (function_head * bind_matches)
  | `Bind of bind
]

and declaration = [
    `Decl of decl
  | `Type_syno of (
        Token.t (* "type" *) * type_head * Token.t (* "=" *) * ktype
    )
  | `Kind_sign of (
        Token.t (* "type" *) * type_head * colon2 * gadt_con_prefix
    )
  | `Type_family of (
        Token.t (* "type" *)
      * Token.t (* "family" *)
      * tyfam
      * (
            where
          * [
                `Tyfam_equats of tyfam_equations
              | `Abst_family of abstract_family
            ]
              option
        )
          option
    )
  | `Type_inst_ of (
        Token.t (* "type" *) * Token.t (* "instance" *) * type_instance
    )
  | `Role_anno of (
        Token.t (* "type" *)
      * Token.t (* "role" *)
      * tycons
      * type_role list (* one or more *)
    )
  | `Data_type of (Token.t (* "type" *) option * Token.t (* "data" *) * data)
  | `Newt of (
        Token.t (* "newtype" *)
      * context option
      * type_head
      * newtype_
    )
  | `Data_family of (Token.t (* "data" *) * Token.t (* "family" *) * datafam)
  | `Data_inst of data_instance
  | `Class of (
        Token.t (* "class" *)
      * context option
      * type_head
      * fundeps option
      * (where * class_declarations option) option
    )
  | `Inst of (instance_ * (where * instance_declarations option) option)
  | `Defa_types of (
        Token.t (* "default" *)
      * paren_open
      * (ktype * (Token.t (* "," *) * ktype) list (* zero or more *)) option
      * paren_close
    )
  | `Deri_inst of (
        phantom_deriving (*tok*) option
      * Token.t (* "deriving" *)
      * [ `Deri_stra of deriving_strategy | `Via of via ] option
      * instance_
    )
  | `Pat_syno of (
        Token.t (* "pattern" *)
      * [
            `Patsyn_sign of patsyn_signature
          | `Patsyn_equa of patsyn_equation
        ]
    )
  | `Fore_import of (
        Token.t (* "foreign" *)
      * Token.t (* "import" *)
      * calling_convention (*tok*)
      * safety (*tok*) option
      * string_ (*tok*) option
      * signature
    )
  | `Fore_export of (
        Token.t (* "foreign" *)
      * Token.t (* "export" *)
      * calling_convention (*tok*)
      * string_ (*tok*) option
      * signature
    )
  | `Fixity of fixity
  | `Top_splice of top_splice
]

and deriving = (
    phantom_deriving (*tok*) option
  * Token.t (* "deriving" *)
  * deriving_strategy option
  * constraint_
  * via option
)

and exp = [
    `Exp_sign of (top_splice * colon2 * gadt_con_prefix)
  | `Exp of top_splice
]

and exp_greedy = [
    `Exp_lambda of (Token.t (* "\\" *) * patterns * arrow * exp_statement)
  | `Exp_let_in of (
        Token.t (* "let" *)
      * let_binds option
      * phantom_in (*tok*) option
      * Token.t (* "in" *)
      * exp_statement
    )
  | `Exp_cond of (
        Token.t (* "if" *)
      * exp_statement
      * Token.t (* ";" *) list (* zero or more *)
      * Token.t (* "then" *)
      * exp_statement
      * Token.t (* ";" *) list (* zero or more *)
      * Token.t (* "else" *)
      * exp_statement
    )
]

and exp_parens = (paren_open * exp_statement * paren_close)

and exp_statement = exp

and exp_th_quoted_name = [
    `SQUOT_choice_choice_choice_var of (Token.t (* "'" *) * qname)
  | `SQUOTSQUOT_type of (Token.t (* "''" *) * newtype_con_field)
]

and exp_tuple_elems = (
    [
        `Rep1_COMMA_exp of (
            Token.t (* "," *) list (* one or more *)
          * exp_statement
        )
      | `Exp_COMMA_opt_exp of (
            exp_statement
          * Token.t (* "," *)
          * exp_statement option
        )
    ]
  * anon_rep_COMMA_opt_exp_stmt_38c9686
)

and explicit_type = (
    paren_open * Token.t (* "type" *) * newtype_con_field * paren_close
)

and expression = [
    `Exp_infix of (
        top_splice
      * cond_no_section_op (*tok*) option
      * [
            `Cond_minus_op_minus of (cond_minus (*tok*) * Token.t (* "-" *))
          | `Exp_op of exp_op
          | `Cond_qual_op_choice_qual_varsym of (
                cond_qualified_op (*tok*) * qsym
            )
        ]
      * top_splice
    )
  | `Exp_nega of (Token.t (* "-" *) * top_splice)
  | `Exp_apply of (
        top_splice
      * [
            `Exp of top_splice
          | `At_type of at_type
          | `Expl_type of explicit_type
        ]
    )
  | `Exp_record of (
        top_splice
      * Token.t (* "{" *)
      * cmd_brace_open (*tok*)
      * (
            field_update
          * (Token.t (* "," *) * field_update) list (* zero or more *)
        )
          option
      * Token.t (* "}" *)
      * cmd_brace_close (*tok*)
    )
  | `Exp_proj of (top_splice * tight_dot * variable (*tok*))
  | `Exp_arit_seq of (
        bracket_open
      * exp_statement
      * (Token.t (* "," *) * exp_statement) option
      * dotdot
      * exp_statement option
      * bracket_close
    )
  | `Exp_list_comp of (
        bracket_open
      * exp_statement
      * (Token.t (* "|" *) * qualifiers) list (* one or more *)
      * bracket_close
    )
  | `Exp_unbo_tuple of (
        unboxed_open
      * Token.t (* "," *) list (* zero or more *)
      * exp_statement
      * anon_rep_COMMA_opt_exp_stmt_38c9686
      * unboxed_close
    )
  | `Exp_unbo_sum of (
        unboxed_open
      * [
            `Rep1_choice_BAR_exp of (
                unboxed_bar list (* one or more *)
              * exp_statement
            )
          | `Exp_choice_BAR of (exp_statement * unboxed_bar)
        ]
      * unboxed_bar list (* zero or more *)
      * unboxed_close
    )
  | `Exp_proj_sele of (
        paren_open
      * any_prefix_dot
      * variable (*tok*)
      * (tight_dot * variable (*tok*)) list (* zero or more *)
      * paren_close
    )
  | `Exp_quote of (
        [
            `Choice_UNKUNKUNK_opt_exp of (
                [
                    `UNKUNKUNK of Token.t (* "\226\159\166" *)
                  | `Cond_quote_start_LBRACK_opt_e_BAR of (
                        cond_quote_start (*tok*)
                      * Token.t (* "[" *)
                      * Token.t (* "e" *) option
                      * Token.t (* "|" *)
                    )
                ]
              * exp_statement option
            )
          | `Cond_quote_start_LBRACK_t_BAR_opt_ktype of (
                cond_quote_start (*tok*)
              * Token.t (* "[" *)
              * Token.t (* "t" *)
              * Token.t (* "|" *)
              * ktype option
            )
          | `Cond_quote_start_LBRACK_p_BAR_opt_pat of (
                cond_quote_start (*tok*)
              * Token.t (* "[" *)
              * Token.t (* "p" *)
              * Token.t (* "|" *)
              * pat option
            )
          | `Cond_quote_start_LBRACK_d_BAR_opt_quoted_decls of (
                cond_quote_start (*tok*)
              * Token.t (* "[" *)
              * Token.t (* "d" *)
              * Token.t (* "|" *)
              * quoted_decls option
            )
        ]
      * anon_choice_tok_barr_720cf3d
    )
  | `Exp_typed_quote of (
        cond_quote_start (*tok*)
      * Token.t (* "[" *)
      * Token.t (* "e" *) option
      * Token.t (* "||" *)
      * exp_statement option
      * tok_barbarrbrack (*tok*)
    )
  | `Exp_th_quoted_name of exp_th_quoted_name
  | `Exp_lambda_case of (
        Token.t (* "\\" *)
      * Token.t (* "case" *)
      * alternatives option
    )
  | `Exp_lambda_cases of (
        Token.t (* "\\" *)
      * Token.t (* "cases" *)
      * nalts option
    )
  | `Exp_do of (do_ * statements)
  | `Exp_parens of exp_parens
  | `Exp_tuple of (paren_open * exp_tuple_elems * paren_close)
  | `Exp_list of (
        bracket_open
      * exp_statement
      * (Token.t (* "," *) * exp_statement) list (* zero or more *)
      * Token.t (* "," *) option
      * bracket_close
    )
  | `Plist of plist
  | `Exp_sect_left of (
        paren_open
      * top_splice
      * cond_left_section_op (*tok*)
      * [
            `Exp_op of exp_op
          | `Op_minus of Token.t (* "-" *)
          | `Choice_qual_varsym of qsym
        ]
      * paren_close
    )
  | `Exp_sect_right of (
        paren_open
      * [ `Op_qual_dot_head of operator_qual_dot_head | `Ops of ops ]
      * top_splice
      * paren_close
    )
  | `Choice_exp_lambda of exp_greedy
  | `Exp_case of (
        Token.t (* "case" *)
      * exp_statement
      * Token.t (* "of" *)
      * alternatives option
    )
  | `Exp_multi_way_if of (
        Token.t (* "if" *)
      * cmd_layout_start_if (*tok*)
      * match_ list (* zero or more *)
      * cond_layout_end (*tok*)
    )
  | `Choice_choice_choice_name of exp_name
  | `Choice_splice of universal
]

and field = (
    variable (*tok*)
  * (Token.t (* "," *) * variable (*tok*)) list (* zero or more *)
  * colon2
  * parameter_type
)

and field_pattern = [
    `DOTDOT of Token.t (* ".." *)
  | `Field_names_opt_EQ_choice_view_pat of (
        field_names
      * (Token.t (* "=" *) * pat_texp) option
    )
]

and field_type = [
    `Strict_field of strict_field
  | `Lazy_field of lazy_field
  | `Type of newtype_con_field
]

and field_update = [
    `DOTDOT of Token.t (* ".." *)
  | `Field_spec_opt_EQ_exp of (field_spec * simple_bind_match option)
]

and forall_ = [
    `Forall of (forall_body * Token.t (* "." *))
  | `Forall_requ of (forall_body * arrow)
]

and forall_body = (forall_keyword * quantified_variables option)

and function_head = [
    `Choice_func_name_pattes of (function_head_patterns * patterns)
  | `Func_head_infix of (
        pattern
      * cond_no_section_op (*tok*) option
      * [
            `Cond_minus_op_minus of (cond_minus (*tok*) * Token.t (* "-" *))
          | `Choice_op of varop
        ]
      * pattern
    )
]

and function_head_patterns = [
    `Func_name of function_name
  | `Func_head_parens of (
        paren_open
      * [
            `Choice_choice_func_name_pattes of function_head
          | `Choice_func_name of function_head_patterns
        ]
      * paren_close
    )
]

and gadt = (type_annotation option * where * gadt_constructors option)

and gadt_con_prefix = quantified_type

and gadt_con_record = (record_fields * fun_arrow * gadt_con_prefix)

and gadt_constructor = (
    anon_choice_con_8c8f04c
  * colon2
  * forall_ option
  * context option
  * [
        `Gadt_con_prefix of gadt_con_prefix
      | `Gadt_con_record of gadt_con_record
    ]
)

and gadt_constructors = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * gadt_constructor
      * (anon_choice_rep1_SEMI_eece391 * gadt_constructor)
          list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and generator = (pat * larrow * exp_statement)

and guard = [ `Gene of generator | `Let_ of let__ | `Exp of exp_statement ]

and guards = (guard * (Token.t (* "," *) * guard) list (* zero or more *))

and guards_ = (bar * cmd_texp_start (*tok*) * guards)

and implicit_parameter = (
    implicit_variable (*tok*) * colon2 * gadt_con_prefix
)

and inferred_tyvar = (
    Token.t (* "{" *) * cmd_brace_open (*tok*) * ktype_param
  * Token.t (* "}" *) * cmd_brace_close (*tok*)
)

and inst_adt = (
    forall_ option
  * context option
  * type_instance_head
  * data_rhs option
  * deriving list (* zero or more *)
)

and inst_newtype = (
    forall_ option
  * context option
  * type_instance_head
  * newtype_
)

and instance_ = (
    Token.t (* "instance" *)
  * forall_ option
  * context option
  * type_instance_head
)

and instance_decl = [
    `Decl of decl
  | `Assoc_data of assoc_datainst
  | `Assoc_tyinst of assoc_tyinst
]

and instance_declarations = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * instance_decl
      * (anon_choice_rep1_SEMI_eece391 * instance_decl)
          list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and ktype = [
    `Type_sign of (gadt_con_prefix * colon2 * gadt_con_prefix)
  | `Quan_type of gadt_con_prefix
]

and ktype_param = [
    `Type_param of type_param
  | `Type_param_anno of (type_param * colon2 * gadt_con_prefix)
]

and lazy_field = (any_prefix_tilde * newtype_con_field)

and let__ = (Token.t (* "let" *) * let_binds option)

and let_binds = (
    [
        `Cmd_layout_start_let of cmd_layout_start_let (*tok*)
      | `Cmd_layout_start_expl of cmd_layout_start_explicit (*tok*)
    ]
  * (
        anon_choice_rep1_SEMI_eece391 option
      * decl
      * (anon_choice_rep1_SEMI_eece391 * decl) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and linear_fun_arrow = [
    `Modi_fun_arrow of (modifier * fun_arrow)
  | `Opt_phan_arrow_linear_arrow of (
        phantom_arrow (*tok*) option
      * linear_arrow
    )
]

and local_binds = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * local_decl
      * (anon_choice_rep1_SEMI_eece391 * local_decl) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and local_decl = [ `Fixity of fixity | `Decl of decl ]

and match_ = (
    guards_
  * phantom_arrow (*tok*) option
  * arrow
  * cmd_texp_end (*tok*)
  * exp_statement
)

and matches = [
    `Simple_match of (arrow * exp_statement)
  | `Rep1_match of match_ list (* one or more *)
]

and modifier = (prefix_percent * newtype_con_field)

and nalt = (patterns * matches * where_binds option)

and nalts = (
    anon_choice_cmd_layout_start_case_8ec747f
  * (
        anon_choice_rep1_SEMI_eece391 option
      * nalt
      * (anon_choice_rep1_SEMI_eece391 * nalt) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and newtype_ = (
    [
        `EQ_newt_cons of (Token.t (* "=" *) * newtype_constructor)
      | `Gadt of gadt
    ]
  * deriving list (* zero or more *)
)

and newtype_con_field = type_

and newtype_constructor = (
    con
  * [
        `Newt_con_field of newtype_con_field
      | `Record_fields of record_fields
    ]
)

and parameter_type = [
    `Strict_field of strict_field
  | `Lazy_field of lazy_field
  | `Quan_type of gadt_con_prefix
]

and pat = [
    `Pat_sign of (pattern * colon2 * gadt_con_prefix)
  | `Pat of pattern
]

and pat_apply_arg = [
    `Pat of pattern
  | `At_type of at_type
  | `Expl_type of explicit_type
]

and pat_texp = [
    `View_pat of (exp_statement * arrow * pat_texp)
  | `Pat of pat
]

and pat_tuple_elems = (
    pat_texp
  * (Token.t (* "," *) * pat_texp) list (* one or more *)
)

and patsyn_cons = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * bind
      * (anon_choice_rep1_SEMI_eece391 * bind) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and patsyn_equation = (
    pattern
  * [ `EQ of Token.t (* "=" *) | `Larrow of larrow ]
  * pat
  * (where * patsyn_cons option) option
)

and patsyn_signature = (anon_choice_con_8c8f04c * colon2 * gadt_con_prefix)

and pattern = [
    `Pat_infix of (
        pattern
      * cond_no_section_op (*tok*) option
      * [
            `Cons_op of consym (*tok*)
          | `Choice_cons_ticked of conids_ticked
          | `Cond_qual_op_qual_consym of (
                cond_qualified_op (*tok*) * qconsym
            )
        ]
      * pattern
    )
  | `Pat_nega of (Token.t (* "-" *) * number)
  | `Pat_apply of (pattern * pat_apply_arg)
  | `Choice_choice_var of pat_name
  | `Pat_as of (variable (*tok*) * tight_at * pattern)
  | `Pat_record of (
        pattern
      * Token.t (* "{" *)
      * cmd_brace_open (*tok*)
      * (
            field_pattern
          * (Token.t (* "," *) * field_pattern) list (* zero or more *)
        )
          option
      * Token.t (* "}" *)
      * cmd_brace_close (*tok*)
    )
  | `Pat_wild of Token.t (* "_" *)
  | `Pat_parens of (paren_open * pat_texp * paren_close)
  | `Pat_tuple of (paren_open * pat_tuple_elems * paren_close)
  | `Pat_unbo_tuple of (
        unboxed_open
      * pat_texp
      * (Token.t (* "," *) * pat_texp) list (* zero or more *)
      * unboxed_close
    )
  | `Pat_unbo_sum of (
        unboxed_open
      * [
            `Rep1_choice_BAR_choice_view_pat of (
                unboxed_bar list (* one or more *)
              * pat_texp
            )
          | `Choice_view_pat_choice_BAR of (pat_texp * unboxed_bar)
        ]
      * unboxed_bar list (* zero or more *)
      * unboxed_close
    )
  | `Pat_list of (
        bracket_open
      * pat_texp
      * (Token.t (* "," *) * pat_texp) list (* zero or more *)
      * Token.t (* "," *) option
      * bracket_close
    )
  | `Plist of plist
  | `Pat_strict of (any_prefix_bang * pattern)
  | `Pat_irre of (any_prefix_tilde * pattern)
  | `Choice_splice of universal
]

and patterns = pat_apply_arg list (* one or more *)

and qualifier = [
    `Gene of generator
  | `Let_ of let__
  | `Tran of (
        Token.t (* "then" *)
      * exp_statement
      * (Token.t (* "by" *) * exp_statement) option
    )
  | `Group of (
        Token.t (* "then" *)
      * Token.t (* "group" *)
      * (Token.t (* "by" *) * exp_statement) option
      * Token.t (* "using" *)
      * exp_statement
    )
  | `Exp of exp_statement
]

and qualifiers = (
    qualifier
  * (Token.t (* "," *) * qualifier) list (* zero or more *)
)

and quantified_type = [
    `Qtype_func of (parameter_type * fun_arrow * gadt_con_prefix)
  | `Qtype_linear_func of (
        parameter_type * linear_fun_arrow * gadt_con_prefix
    )
  | `Qtype_forall of (forall_body * Token.t (* "." *) * gadt_con_prefix)
  | `Qtype_forall_requ of (forall_body * arrow * gadt_con_prefix)
  | `Qtype_cont of (context * gadt_con_prefix)
  | `Impl_param of implicit_parameter
  | `Type of newtype_con_field
]

and quantified_variables =
  [ `Type_param of type_param | `Infe_tyvar of inferred_tyvar ]
    list (* one or more *)

and quoted_decls = (
    [
        `Cmd_layout_start_quote of cmd_layout_start_quote (*tok*)
      | `Cmd_layout_start_expl of cmd_layout_start_explicit (*tok*)
    ]
  * (
        anon_choice_rep1_SEMI_eece391 option
      * declaration
      * (anon_choice_rep1_SEMI_eece391 * declaration) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and record_fields = (
    Token.t (* "{" *)
  * cmd_brace_open (*tok*)
  * (field * (Token.t (* "," *) * field) list (* zero or more *)) option
  * Token.t (* "," *) option
  * Token.t (* "}" *)
  * cmd_brace_close (*tok*)
)

and signature = (
    [ `Choice_var of var | `Var_bind_list of var_binding_list ]
  * colon2
  * gadt_con_prefix
)

and simple_bind_match = (Token.t (* "=" *) * exp_statement)

and splice_exp = [
    `Choice_choice_choice_name of exp_name
  | `Exp_parens of exp_parens
  | `Lit of literal
]

and statement = [
    `Exp_stmt of exp_statement
  | `Gene of generator
  | `Let_ of let__
  | `Rec of (Token.t (* "rec" *) * statements)
]

and statements = (
    [
        `Cmd_layout_start_do of cmd_layout_start_do (*tok*)
      | `Cmd_layout_start_expl of cmd_layout_start_explicit (*tok*)
    ]
  * (
        anon_choice_rep1_SEMI_eece391 option
      * statement
      * (anon_choice_rep1_SEMI_eece391 * statement) list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and strict_field = (any_prefix_bang * newtype_con_field)

and top_splice = expression

and tyfam = (
    type_head
  * [ `Colon2_quan_type of type_annotation | `Tyfam_inj of tyfam_inj ] option
)

and tyfam_equations = (
    anon_choice_cmd_layout_start_adad0e7
  * (
        anon_choice_rep1_SEMI_eece391 option
      * type_instance
      * (anon_choice_rep1_SEMI_eece391 * type_instance)
          list (* zero or more *)
      * anon_choice_rep1_SEMI_eece391 option
    )
      option
  * layout_end
)

and tyfam_inj = (type_family_result * type_family_injectivity option)

and type_ = [
    `Choice_var of type_name
  | `Type_star of type_star
  | `Type_wild of Token.t (* "_" *)
  | `Type_parens of (paren_open * ktype * paren_close)
  | `Type_prom of (
        Token.t (* "'" *)
      * [
            `Plist of plist
          | `Type_tuple of type_tuple
          | `Type_list of type_list
          | `Prefix_tuple of prefix_tuple
          | `Unit of unit_
        ]
    )
  | `Type_list of type_list
  | `Plist of plist
  | `Type_unbo_tuple of type_unboxed_tuple
  | `Type_unbo_sum of (
        unboxed_open
      * ktype
      * (unboxed_bar * ktype) list (* one or more *)
      * unboxed_close
    )
  | `Type_tuple of type_tuple
  | `Type_infix of type_infix
  | `Type_apply of (newtype_con_field * type_apply_arg)
  | `Choice_splice of universal
]

and type_annotation = (colon2 * gadt_con_prefix)

and type_apply_arg = [ `Type of newtype_con_field | `At_type of at_type ]

and type_family_result = (Token.t (* "=" *) * gadt_con_prefix)

and type_head = [
    `Type_head_params_opt_type_params of (
        type_head_params
      * type_params option
    )
  | `Type_head_infix of (type_param * tyconops * type_param)
]

and type_head_params = [
    `Type_head_name of type_head_name
  | `Type_head_parens of (
        paren_open
      * [
            `Choice_type_head_params_opt_type_params of type_head
          | `Type_head_params of type_head_params
        ]
      * paren_close
    )
]

and type_infix = (newtype_con_field * tyops * newtype_con_field)

and type_instance = (forall_ option * type_instance_common)

and type_instance_common = (
    type_instance_head * Token.t (* "=" *) * gadt_con_prefix
)

and type_instance_head = [
    `Type_inst_head_params_opt_type_pattes of (
        type_instance_head_params
      * type_patterns option
    )
  | `Cond_infix_type_infix of (cond_infix (*tok*) * type_infix)
]

and type_instance_head_params = [
    `Choice_choice_name of tycons
  | `Type_inst_head_parens of (
        paren_open
      * [
            `Choice_type_inst_head_params_opt_type_pattes of
              type_instance_head
          | `Type_inst_head_params of type_instance_head_params
        ]
      * type_annotation option
      * paren_close
    )
]

and type_list = (
    bracket_open
  * ktype
  * (Token.t (* "," *) * ktype) list (* zero or more *)
  * bracket_close
)

and type_param = [
    `Type_param_wild of Token.t (* "_" *)
  | `Type_param_invi of (prefix_at * type_param)
  | `Type_param_parens of (paren_open * ktype_param * paren_close)
  | `Var of variable (*tok*)
]

and type_params = type_param list (* one or more *)

and type_patterns = type_apply_arg list (* one or more *)

and type_tuple = (paren_open * type_tuple_elems * paren_close)

and type_tuple_elems = (
    ktype
  * (Token.t (* "," *) * ktype) list (* one or more *)
)

and type_unboxed_tuple = (
    unboxed_open
  * ktype
  * (Token.t (* "," *) * ktype) list (* zero or more *)
  * unboxed_close
)

and universal = [
    `Splice of (splice_dollars * splice_exp)
  | `Quas of (
        cond_quote_start (*tok*)
      * Token.t (* "[" *)
      * quoter
      * Token.t (* "|" *)
      * quasiquote_body (*tok*) option
      * anon_choice_tok_barr_720cf3d
    )
  | `Lit of literal
  | `Choice_unit of unit_cons
  | `Choice_prefix_tuple of tuple_cons
]

and via = (Token.t (* "via" *) * gadt_con_prefix)

and where_binds = (where * local_binds option)

type children = (
    paren_open
  * (
        anon_choice_DOTDOT_249879e
      * (Token.t (* "," *) * anon_choice_DOTDOT_249879e)
          list (* zero or more *)
    )
      option
  * paren_close
)

type ie_entity = (
    namespace option
  * [
        `Choice_qvarid of quoter
      | `Choice_qtyc of tyconids
      | `Choice_sym_prefix of [
            `Sym_prefix of sym_prefix
          | `Choice_pqva of pqsym
        ]
    ]
  * children option
)

type import_list = (
    paren_open
  * (ie_entity * (Token.t (* "," *) * ie_entity) list (* zero or more *))
      option
  * Token.t (* "," *) option
  * paren_close
)

type anon_choice_ie_entity_50c17c0 = [
    `Ie_entity of ie_entity
  | `Module_export of (Token.t (* "module" *) * module_)
]

type import = (
    Token.t (* "import" *)
  * Token.t (* "qualified" *) option
  * string_ (*tok*) option
  * module_
  * Token.t (* "qualified" *) option
  * (Token.t (* "as" *) * module_) option
  * (Token.t (* "hiding" *) option * import_list) option
)

type exports = (
    paren_open
  * (
        anon_choice_ie_entity_50c17c0
      * (Token.t (* "," *) * anon_choice_ie_entity_50c17c0)
          list (* zero or more *)
    )
      option
  * Token.t (* "," *) option
  * paren_close
)

type imports = (
    import
  * (anon_choice_rep1_SEMI_eece391 * import) list (* zero or more *)
  * anon_choice_rep1_SEMI_eece391
)

type declarations = (
    declaration
  * (
        anon_choice_rep1_SEMI_eece391
      * [ `Decl of declaration | `Import of import ]
    )
      list (* zero or more *)
  * anon_choice_rep1_SEMI_eece391 option
)

type header = (Token.t (* "module" *) * module_ * exports option * where)

type body = (
    anon_choice_cmd_layout_start_adad0e7
  * anon_choice_rep1_SEMI_eece391 option
  * imports option
  * declarations option
  * layout_end
)

type haskell = (header option * body option)

type haddock (* inlined *) = Token.t

type operator_minus (* inlined *) = Token.t (* "-" *)

type pat_wildcard (* inlined *) = Token.t (* "_" *)

type type_wildcard (* inlined *) = Token.t (* "_" *)

type type_param_wildcard (* inlined *) = Token.t (* "_" *)

type pragma (* inlined *) = Token.t

type comment (* inlined *) = Token.t

type cpp (* inlined *) = Token.t

type promote (* inlined *) = Token.t (* "'" *)

type error_sentinel (* inlined *) = Token.t

type entity (* inlined *) = string_ (*tok*)

type tight_bang (* inlined *) = (cond_tight_bang (*tok*) * Token.t (* "!" *))

type prefix_tilde (* inlined *) = (
    cond_prefix_tilde (*tok*) * Token.t (* "~" *)
)

type field_name (* inlined *) = variable (*tok*)

type operator_hash_head (* inlined *) = (
    [ `HASH of Token.t (* "#" *) | `Imm_tok_hash of imm_tok_hash (*tok*) ]
  * [
        `Imm_tok_hash of imm_tok_hash (*tok*)
      | `Imm_tok_bar of imm_tok_bar (*tok*)
    ]
      option
)

type modid (* inlined *) = name (*tok*)

type constructor (* inlined *) = name (*tok*)

type tyconid (* inlined *) = name (*tok*)

type prefix_bang (* inlined *) = (
    cond_prefix_bang (*tok*) * Token.t (* "!" *)
)

type constructor_operator (* inlined *) = consym (*tok*)

type fun_arrow_fixity (* inlined *) = (
    Token.t (* "infixr" *) * fun_arrow_prec * Token.t (* "->" *)
)

type tight_tilde (* inlined *) = (
    cond_tight_tilde (*tok*) * Token.t (* "~" *)
)

type tycon_ticked (* inlined *) = (
    Token.t (* "`" *) * name (*tok*) * Token.t (* "`" *)
)

type constructor_operator_alias (* inlined *) = consym (*tok*)

type tycon_arrow (* inlined *) = (paren_open * arrow * paren_close)

type exp_projection_selector (* inlined *) = (
    paren_open
  * any_prefix_dot
  * variable (*tok*)
  * (tight_dot * variable (*tok*)) list (* zero or more *)
  * paren_close
)

type pat_negation (* inlined *) = (Token.t (* "-" *) * number)

type prefix_unboxed_sum (* inlined *) = (
    unboxed_open
  * unboxed_bar list (* one or more *)
  * unboxed_close
)

type prefix_unboxed_tuple (* inlined *) = (
    unboxed_open
  * Token.t (* "," *) list (* one or more *)
  * unboxed_close
)

type do_module (* inlined *) = (qualifying_module * do_keyword)

type qfield_name (* inlined *) = (qualifying_module * variable (*tok*))

type module_export (* inlined *) = (Token.t (* "module" *) * module_)

type qtycon_arrow (* inlined *) = (
    paren_open * qualified_arrow * paren_close
)

type con_binding_list (* inlined *) = (
    con
  * (Token.t (* "," *) * con) list (* one or more *)
)

type qtycon_ticked (* inlined *) = (
    Token.t (* "`" *) * qtyconid * Token.t (* "`" *)
)

type varids (* inlined *) = [ `Qvarid of qvarid | `Var of variable (*tok*) ]

type qvariable_ticked (* inlined *) = (
    Token.t (* "`" *) * qvarid * Token.t (* "`" *)
)

type qconstructor_ticked (* inlined *) = (
    Token.t (* "`" *) * qconid * Token.t (* "`" *)
)

type conids (* inlined *) = [ `Qconid of qconid | `Name of name (*tok*) ]

type field_path (* inlined *) = (
    field_names
  * (tight_dot * variable (*tok*)) list (* one or more *)
)

type name_ (* inlined *) = [ `Choice_var of var | `Choice_name of con ]

type child_type (* inlined *) = (Token.t (* "type" *) * tyconids)

type quasiquote (* inlined *) = (
    cond_quote_start (*tok*)
  * Token.t (* "[" *)
  * quoter
  * Token.t (* "|" *)
  * quasiquote_body (*tok*) option
  * anon_choice_tok_barr_720cf3d
)

type promoted_tyconops (* inlined *) = promoted_tyconops_alias

type role_annotation (* inlined *) = (
    Token.t (* "type" *)
  * Token.t (* "role" *)
  * tycons
  * type_role list (* one or more *)
)

type promoted_tycons (* inlined *) = promoted_tycons_alias

type assoc_datafam (* inlined *) = (
    Token.t (* "data" *)
  * Token.t (* "family" *) option
  * datafam
)

type assoc_datainst_adt (* inlined *) = (
    Token.t (* "data" *)
  * Token.t (* "instance" *) option
  * inst_adt
)

type assoc_datainst_newtype (* inlined *) = (
    Token.t (* "newtype" *)
  * Token.t (* "instance" *) option
  * inst_newtype
)

type assoc_tyfam (* inlined *) = (
    Token.t (* "type" *)
  * Token.t (* "family" *) option
  * type_head
  * [
        `Colon2_quan_type of type_annotation
      | `Type_family_result_type_family_inje of (
            type_family_result * type_family_injectivity
        )
    ]
      option
)

type class_ (* inlined *) = (
    Token.t (* "class" *)
  * context option
  * type_head
  * fundeps option
  * (where * class_declarations option) option
)

type class_apply (* inlined *) = (constraint_ * type_apply_arg)

type class_infix (* inlined *) = (
    cond_infix (*tok*) * newtype_con_field * tyops * newtype_con_field
)

type ctr_context (* inlined *) = (context * constraints)

type ctr_forall (* inlined *) = (
    forall_body * Token.t (* "." *) * constraints
)

type ctr_parens (* inlined *) = (paren_open * constraints * paren_close)

type ctr_signature (* inlined *) = (constraints * colon2 * gadt_con_prefix)

type ctr_tuple (* inlined *) = (
    paren_open
  * constraints
  * (Token.t (* "," *) * constraints) list (* one or more *)
  * paren_close
)

type data_family (* inlined *) = (
    Token.t (* "data" *) * Token.t (* "family" *) * datafam
)

type data_type (* inlined *) = (
    Token.t (* "type" *) option
  * Token.t (* "data" *)
  * data
)

type datacon_unboxed_sum (* inlined *) = (
    unboxed_open
  * [
        `Rep1_choice_BAR_quan_type of (
            unboxed_bar list (* one or more *)
          * gadt_con_prefix
        )
      | `Quan_type_choice_BAR of (gadt_con_prefix * unboxed_bar)
    ]
  * unboxed_bar list (* zero or more *)
  * unboxed_close
)

type decl_inst_adt (* inlined *) = (
    Token.t (* "data" *) * Token.t (* "instance" *) * inst_adt
)

type decl_inst_newtype (* inlined *) = (
    Token.t (* "newtype" *) * Token.t (* "instance" *) * inst_newtype
)

type default_signature (* inlined *) = (Token.t (* "default" *) * signature)

type default_types (* inlined *) = (
    Token.t (* "default" *)
  * paren_open
  * (ktype * (Token.t (* "," *) * ktype) list (* zero or more *)) option
  * paren_close
)

type deriving_instance (* inlined *) = (
    phantom_deriving (*tok*) option
  * Token.t (* "deriving" *)
  * [ `Deri_stra of deriving_strategy | `Via of via ] option
  * instance_
)

type exp_apply (* inlined *) = (
    top_splice
  * [
        `Exp of top_splice
      | `At_type of at_type
      | `Expl_type of explicit_type
    ]
)

type exp_arithmetic_sequence (* inlined *) = (
    bracket_open
  * exp_statement
  * (Token.t (* "," *) * exp_statement) option
  * dotdot
  * exp_statement option
  * bracket_close
)

type exp_case (* inlined *) = (
    Token.t (* "case" *)
  * exp_statement
  * Token.t (* "of" *)
  * alternatives option
)

type exp_conditional (* inlined *) = (
    Token.t (* "if" *)
  * exp_statement
  * Token.t (* ";" *) list (* zero or more *)
  * Token.t (* "then" *)
  * exp_statement
  * Token.t (* ";" *) list (* zero or more *)
  * Token.t (* "else" *)
  * exp_statement
)

type exp_do (* inlined *) = (do_ * statements)

type exp_infix (* inlined *) = (
    top_splice
  * cond_no_section_op (*tok*) option
  * [
        `Cond_minus_op_minus of (cond_minus (*tok*) * Token.t (* "-" *))
      | `Exp_op of exp_op
      | `Cond_qual_op_choice_qual_varsym of (
            cond_qualified_op (*tok*) * qsym
        )
    ]
  * top_splice
)

type exp_lambda (* inlined *) = (
    Token.t (* "\\" *) * patterns * arrow * exp_statement
)

type exp_lambda_case (* inlined *) = (
    Token.t (* "\\" *)
  * Token.t (* "case" *)
  * alternatives option
)

type exp_lambda_cases (* inlined *) = (
    Token.t (* "\\" *)
  * Token.t (* "cases" *)
  * nalts option
)

type exp_let_in (* inlined *) = (
    Token.t (* "let" *)
  * let_binds option
  * phantom_in (*tok*) option
  * Token.t (* "in" *)
  * exp_statement
)

type exp_list (* inlined *) = (
    bracket_open
  * exp_statement
  * (Token.t (* "," *) * exp_statement) list (* zero or more *)
  * Token.t (* "," *) option
  * bracket_close
)

type exp_list_comprehension (* inlined *) = (
    bracket_open
  * exp_statement
  * (Token.t (* "|" *) * qualifiers) list (* one or more *)
  * bracket_close
)

type exp_multi_way_if (* inlined *) = (
    Token.t (* "if" *)
  * cmd_layout_start_if (*tok*)
  * match_ list (* zero or more *)
  * cond_layout_end (*tok*)
)

type exp_negation (* inlined *) = (Token.t (* "-" *) * top_splice)

type exp_projection (* inlined *) = (
    top_splice * tight_dot * variable (*tok*)
)

type exp_quote (* inlined *) = (
    [
        `Choice_UNKUNKUNK_opt_exp of (
            [
                `UNKUNKUNK of Token.t (* "\226\159\166" *)
              | `Cond_quote_start_LBRACK_opt_e_BAR of (
                    cond_quote_start (*tok*)
                  * Token.t (* "[" *)
                  * Token.t (* "e" *) option
                  * Token.t (* "|" *)
                )
            ]
          * exp_statement option
        )
      | `Cond_quote_start_LBRACK_t_BAR_opt_ktype of (
            cond_quote_start (*tok*)
          * Token.t (* "[" *)
          * Token.t (* "t" *)
          * Token.t (* "|" *)
          * ktype option
        )
      | `Cond_quote_start_LBRACK_p_BAR_opt_pat of (
            cond_quote_start (*tok*)
          * Token.t (* "[" *)
          * Token.t (* "p" *)
          * Token.t (* "|" *)
          * pat option
        )
      | `Cond_quote_start_LBRACK_d_BAR_opt_quoted_decls of (
            cond_quote_start (*tok*)
          * Token.t (* "[" *)
          * Token.t (* "d" *)
          * Token.t (* "|" *)
          * quoted_decls option
        )
    ]
  * anon_choice_tok_barr_720cf3d
)

type exp_record (* inlined *) = (
    top_splice
  * Token.t (* "{" *)
  * cmd_brace_open (*tok*)
  * (
        field_update
      * (Token.t (* "," *) * field_update) list (* zero or more *)
    )
      option
  * Token.t (* "}" *)
  * cmd_brace_close (*tok*)
)

type exp_section_left (* inlined *) = (
    paren_open
  * top_splice
  * cond_left_section_op (*tok*)
  * [
        `Exp_op of exp_op
      | `Op_minus of Token.t (* "-" *)
      | `Choice_qual_varsym of qsym
    ]
  * paren_close
)

type exp_section_right (* inlined *) = (
    paren_open
  * [ `Op_qual_dot_head of operator_qual_dot_head | `Ops of ops ]
  * top_splice
  * paren_close
)

type exp_signature (* inlined *) = (top_splice * colon2 * gadt_con_prefix)

type exp_tuple (* inlined *) = (paren_open * exp_tuple_elems * paren_close)

type exp_typed_quote (* inlined *) = (
    cond_quote_start (*tok*)
  * Token.t (* "[" *)
  * Token.t (* "e" *) option
  * Token.t (* "||" *)
  * exp_statement option
  * tok_barbarrbrack (*tok*)
)

type exp_unboxed_sum (* inlined *) = (
    unboxed_open
  * [
        `Rep1_choice_BAR_exp of (
            unboxed_bar list (* one or more *)
          * exp_statement
        )
      | `Exp_choice_BAR of (exp_statement * unboxed_bar)
    ]
  * unboxed_bar list (* zero or more *)
  * unboxed_close
)

type exp_unboxed_tuple (* inlined *) = (
    unboxed_open
  * Token.t (* "," *) list (* zero or more *)
  * exp_statement
  * anon_rep_COMMA_opt_exp_stmt_38c9686
  * unboxed_close
)

type forall (* inlined *) = (forall_body * Token.t (* "." *))

type forall_required (* inlined *) = (forall_body * arrow)

type foreign_export (* inlined *) = (
    Token.t (* "foreign" *)
  * Token.t (* "export" *)
  * calling_convention (*tok*)
  * string_ (*tok*) option
  * signature
)

type foreign_import (* inlined *) = (
    Token.t (* "foreign" *)
  * Token.t (* "import" *)
  * calling_convention (*tok*)
  * safety (*tok*) option
  * string_ (*tok*) option
  * signature
)

type function_ (* inlined *) = (function_head * bind_matches)

type function_head_infix (* inlined *) = (
    pattern
  * cond_no_section_op (*tok*) option
  * [
        `Cond_minus_op_minus of (cond_minus (*tok*) * Token.t (* "-" *))
      | `Choice_op of varop
    ]
  * pattern
)

type function_head_parens (* inlined *) = (
    paren_open
  * [
        `Choice_choice_func_name_pattes of function_head
      | `Choice_func_name of function_head_patterns
    ]
  * paren_close
)

type group (* inlined *) = (
    Token.t (* "then" *)
  * Token.t (* "group" *)
  * (Token.t (* "by" *) * exp_statement) option
  * Token.t (* "using" *)
  * exp_statement
)

type instance (* inlined *) = (
    instance_
  * (where * instance_declarations option) option
)

type kind_signature (* inlined *) = (
    Token.t (* "type" *) * type_head * colon2 * gadt_con_prefix
)

type newtype (* inlined *) = (
    Token.t (* "newtype" *)
  * context option
  * type_head
  * newtype_
)

type pat_apply (* inlined *) = (pattern * pat_apply_arg)

type pat_as (* inlined *) = (variable (*tok*) * tight_at * pattern)

type pat_infix (* inlined *) = (
    pattern
  * cond_no_section_op (*tok*) option
  * [
        `Cons_op of consym (*tok*)
      | `Choice_cons_ticked of conids_ticked
      | `Cond_qual_op_qual_consym of (cond_qualified_op (*tok*) * qconsym)
    ]
  * pattern
)

type pat_irrefutable (* inlined *) = (any_prefix_tilde * pattern)

type pat_list (* inlined *) = (
    bracket_open
  * pat_texp
  * (Token.t (* "," *) * pat_texp) list (* zero or more *)
  * Token.t (* "," *) option
  * bracket_close
)

type pat_parens (* inlined *) = (paren_open * pat_texp * paren_close)

type pat_record (* inlined *) = (
    pattern
  * Token.t (* "{" *)
  * cmd_brace_open (*tok*)
  * (
        field_pattern
      * (Token.t (* "," *) * field_pattern) list (* zero or more *)
    )
      option
  * Token.t (* "}" *)
  * cmd_brace_close (*tok*)
)

type pat_signature (* inlined *) = (pattern * colon2 * gadt_con_prefix)

type pat_strict (* inlined *) = (any_prefix_bang * pattern)

type pat_tuple (* inlined *) = (paren_open * pat_tuple_elems * paren_close)

type pat_unboxed_sum (* inlined *) = (
    unboxed_open
  * [
        `Rep1_choice_BAR_choice_view_pat of (
            unboxed_bar list (* one or more *)
          * pat_texp
        )
      | `Choice_view_pat_choice_BAR of (pat_texp * unboxed_bar)
    ]
  * unboxed_bar list (* zero or more *)
  * unboxed_close
)

type pat_unboxed_tuple (* inlined *) = (
    unboxed_open
  * pat_texp
  * (Token.t (* "," *) * pat_texp) list (* zero or more *)
  * unboxed_close
)

type pattern_synonym (* inlined *) = (
    Token.t (* "pattern" *)
  * [ `Patsyn_sign of patsyn_signature | `Patsyn_equa of patsyn_equation ]
)

type qtype_context (* inlined *) = (context * gadt_con_prefix)

type qtype_forall (* inlined *) = (
    forall_body * Token.t (* "." *) * gadt_con_prefix
)

type qtype_forall_required (* inlined *) = (
    forall_body * arrow * gadt_con_prefix
)

type qtype_function (* inlined *) = (
    parameter_type * fun_arrow * gadt_con_prefix
)

type qtype_linear_function (* inlined *) = (
    parameter_type * linear_fun_arrow * gadt_con_prefix
)

type rec_ (* inlined *) = (Token.t (* "rec" *) * statements)

type simple_match (* inlined *) = (arrow * exp_statement)

type splice (* inlined *) = (splice_dollars * splice_exp)

type transform (* inlined *) = (
    Token.t (* "then" *)
  * exp_statement
  * (Token.t (* "by" *) * exp_statement) option
)

type type_apply (* inlined *) = (newtype_con_field * type_apply_arg)

type type_family (* inlined *) = (
    Token.t (* "type" *)
  * Token.t (* "family" *)
  * tyfam
  * (
        where
      * [
            `Tyfam_equats of tyfam_equations
          | `Abst_family of abstract_family
        ]
          option
    )
      option
)

type type_head_infix (* inlined *) = (type_param * tyconops * type_param)

type type_head_parens (* inlined *) = (
    paren_open
  * [
        `Choice_type_head_params_opt_type_params of type_head
      | `Type_head_params of type_head_params
    ]
  * paren_close
)

type type_instance_ (* inlined *) = (
    Token.t (* "type" *) * Token.t (* "instance" *) * type_instance
)

type type_instance_head_parens (* inlined *) = (
    paren_open
  * [
        `Choice_type_inst_head_params_opt_type_pattes of type_instance_head
      | `Type_inst_head_params of type_instance_head_params
    ]
  * type_annotation option
  * paren_close
)

type type_param_annotated (* inlined *) = (
    type_param * colon2 * gadt_con_prefix
)

type type_param_invisible (* inlined *) = (prefix_at * type_param)

type type_param_parens (* inlined *) = (
    paren_open * ktype_param * paren_close
)

type type_parens (* inlined *) = (paren_open * ktype * paren_close)

type type_promoted (* inlined *) = (
    Token.t (* "'" *)
  * [
        `Plist of plist
      | `Type_tuple of type_tuple
      | `Type_list of type_list
      | `Prefix_tuple of prefix_tuple
      | `Unit of unit_
    ]
)

type type_signature (* inlined *) = (
    gadt_con_prefix * colon2 * gadt_con_prefix
)

type type_synomym (* inlined *) = (
    Token.t (* "type" *) * type_head * Token.t (* "=" *) * ktype
)

type type_unboxed_sum (* inlined *) = (
    unboxed_open
  * ktype
  * (unboxed_bar * ktype) list (* one or more *)
  * unboxed_close
)

type view_pattern (* inlined *) = (exp_statement * arrow * pat_texp)

type let_ (* inlined *) = (Token.t (* "let" *) * let_binds option)

type kind_annotation (* inlined *) = (colon2 * gadt_con_prefix)

type extra = [
    `Cpp of Loc.t * cpp
  | `Comment of Loc.t * comment
  | `Haddock of Loc.t * haddock
  | `Pragma of Loc.t * pragma
]

type extras = extra list
