; required to install tree_sitter/parser.h
(include_subdirs qualified)

(library
 (name tree_sitter_haskell)
 (public_name tree-sitter-lang.haskell)
 (libraries atdgen-runtime tree-sitter.run commons ast_generic lib_parsing lib_parsing_tree_sitter)

 ; A copy of the C headers for the tree-sitter library is found locally.
 (foreign_stubs
  (language c)
  (names parser bindings)
  (flags -std=c99
         -fPIC
         -I %{env:TREESITTER_INCDIR=/usr/local/include}
         -I .))

 (c_library_flags
  (
    -L%{env:TREESITTER_LIBDIR=/usr/local/lib}
    -lstdc++
    -ltree-sitter
    -Wl,-rpath,%{env:TREESITTER_LIBDIR=/usr/local/lib}
  ))

 (foreign_stubs
  (language c)
  (names scanner)
  (flags -std=c99
         -fPIC
         -I %{env:TREESITTER_INCDIR=/usr/local/include}
         -I .)))
